trigger:
  - main

pool:
  name: Default

variables:
  dockerUsername: 'vipulpatodi'

steps:

# Install Node.js
- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Install Node.js'

# Build React App
- script: |
    cd frontend/ui-app
    npm install
    npm run build
  displayName: 'Build React App'

# Build .NET App
- script: |
    cd backend/services/CatalogService
    dotnet restore
    dotnet build --configuration Release
  displayName: 'Build .NET App'

# Docker Login
- script: |
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  displayName: 'Docker Login'
  env:
    DOCKER_USERNAME: $(dockerUsername)
    DOCKER_PASSWORD: $(dockerPassword)

# Build & Push Catalog Service
- script: |
    docker build -t $(dockerUsername)/easyshop-catalog-service:latest ./backend/services/CatalogService
    docker push $(dockerUsername)/easyshop-catalog-service:latest
  displayName: 'Build & Push Catalog Service'

# Build & Push UI App
- script: |
    docker build -t $(dockerUsername)/easyshop-ui-app:latest ./frontend/ui-app
    docker push $(dockerUsername)/easyshop-ui-app:latest
  displayName: 'Build & Push UI App'

# Deploy to AKS
- script: |
    echo "$KUBECONFIG_BASE64" | base64 -d > kubeconfig
    export KUBECONFIG=$(pwd)/kubeconfig

    kubectl get nodes
    kubectl apply -f infra/k8s/

    kubectl rollout restart deployment catalog-deployment
    kubectl rollout restart deployment react-deployment
  displayName: 'Deploy to AKS'
  env:
    KUBECONFIG_BASE64: $(kubeconfigBase64)