version: "3.8"

services:
  catalog-service:
    build: ../../backend/services/CatalogService
    ports:
      - "5001:8080"

  ui-app:
    build: ../../frontend/ui-app
    ports:
      - "3001:80"
    depends_on:
      - catalog-service