apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: vipulpatodi/easyshop-identity-service:latest
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        ports:
        - containerPort: 80