name: Cart CI/CD

on:
  push:
    paths:
      - 'backend/services/CartService/**'

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set tag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Build image
        run: docker build --platform=linux/amd64 -t easyshop-cart-service:${{ env.IMAGE_TAG }} ./backend/services/CartService

      - name: Load into Kind
        run: kind load docker-image easyshop-cart-service:${{ env.IMAGE_TAG }} --name easyshop-cluster

      - name: Deploy
        run: kubectl set image deployment/cart-deployment cart=easyshop-cart-service:${{ env.IMAGE_TAG }}