name: Catalog CI/CD

on:
  push:
    paths:
      - 'backend/services/CatalogService/**'

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Build Docker Image
      - name: Build Docker Image
        run: docker build -t easyshop-catalog-service ./backend/services/CatalogService

      # 3️⃣ Load image into Kind
      - name: Load image into Kind
        run: kind load docker-image easyshop-catalog-service --name easyshop-cluster

      # 4️⃣ Deploy to Kubernetes
      - name: Deploy Catalog
        run: |
          kubectl apply -f infra/k8s/catalog-deployment.yaml
          kubectl apply -f infra/k8s/catalog-service.yaml
          kubectl rollout restart deployment catalog-deployment